### ISSUE TITLE
 gitlab.nobody.run/tbi/socksme 404 not found !

### ISSUE THREAD

**Issue by mehrdad-khojastefar** [LeakIX/l9format#6]
`go: github.com/LeakIX/l9format@v1.3.0 requires
        gitlab.nobody.run/tbi/socksme@v0.0.0-20201130024528-3ad02d4108c5: unrecognized import path "gitlab.nobody.run/tbi/socksme": reading https://gitlab.nobody.run/tbi/socksme?go-get=1: 404 Not Found
        server response: 404 page not found
go: github.com/LeakIX/l9format@v1.3.0 requires
        gitlab.nobody.run/tbi/socksme@v0.0.0-20201130024528-3ad02d4108c5: unrecognized import path "gitlab.nobody.run/tbi/socksme": reading https://gitlab.nobody.run/tbi/socksme?go-get=1: 404 Not Found
        server response: 404 page not found`

when building l9explorer

**Comment by gboddin** [comment]
Hi, 

Thanks for the report, the issue has been resolved in both l9format v1.3.1 and l9explore v1.3.2 !
